name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push prediction-server image
        uses: docker/build-push-action@v4
        with:
          context: ./predicition_server/server2  # Typo retained as requested
          push: true
          tags: ayach2024/prediction-server:latest

      - name: Build and push maj-server image
        uses: docker/build-push-action@v4
        with:
          context: ./training_server
          push: true
          tags: ayach2024/maj-server:latest

  deploy-to-k8s:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubernetes cluster
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config  # Critical fix for kubeconfig
          chmod 600 ~/.kube/config  # Security fix (retained)

      - name: Test Kubernetes connection
        run: kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/persistent-volume.yaml
          kubectl apply -f k8s/persistent-volume-claim.yaml
          kubectl apply -f k8s/prediction-deployment.yaml
          kubectl apply -f k8s/training-deployment.yaml
          kubectl apply -f k8s/prediction-service.yaml
          kubectl apply -f k8s/training-service.yaml
